# Generated by Django 3.0.5 on 2020-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20200418_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
