# Generated by Django 3.0.5 on 2020-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20200418_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
    ]
